### ISSUE TITLE
Permission to refactor the code (minimal) 

### ISSUE THREAD

**Issue by jpzs444** [Tiansing/ScannerOrderJava#1]
Good day, @Tiansing! Do you accept minimal changes in your code? I learned some tips from [Mosh Hamedani](https://www.youtube.com/programmingwithmosh) that can be applied to your program. Also, it is a great practice to use the Pascal Case naming convention for your .java files. Example:  `ordering.java` to `Ordering.java` Thank you for your time and I'm looking forward to your kind response! 😀

**Comment by igbaras** [comment]
> Good day, @Tiansing! Do you accept minimal changes in your code? I learned some tips from [Mosh Hamedani](https://www.youtube.com/programmingwithmosh) that can be applied to your program. Also, it is a great practice to use the Pascal Case naming convention for your .java files. Example: `ordering.java` to `Ordering.java` Thank you for your time and I'm looking forward to your kind response! 😀

Hi @jpzs444 good to hear that, I'll immediately work on that. Thanks for the feedback!
